-- Enable Row Level Security
alter default privileges in schema public grant all on tables to postgres, service_role;

-- 1. GUESTBOOK TABLE
create table if not exists guestbook (
  id bigint generated by default as identity primary key,
  name text not null,
  message text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  is_approved boolean default false -- For moderation if needed
);

-- RLS Policies for Guestbook
alter table guestbook enable row level security;

-- Allow anyone to read approved messages (or all if you prefer)
create policy "Anyone can read guestbook"
  on guestbook for select
  using (true);

-- Allow anyone to insert (sign the guestbook)
create policy "Anyone can sign guestbook"
  on guestbook for insert
  with check (true);

-- 2. SYSTEM_LOGS TABLE (For the "Bug Log" / "Post-Mortem" feature)
create table if not exists system_logs (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null,
  status text check (status in ('investigating', 'resolved', 'monitoring')) default 'investigating',
  level text check (level in ('info', 'warn', 'error', 'fatal')) default 'info',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  resolved_at timestamp with time zone
);

alter table system_logs enable row level security;
create policy "Public read logs" on system_logs for select using (true);
-- Only authenticated users (you) can write logs - configure this later via Supabase Auth or just use the dashboard
